// Package scaffold generates a starting dashdev.yaml from what is already
// in a directory.
//
// Detection is deliberately shallow: the directory itself plus its
// immediate subdirectories, minus places that never contain runnable code
// (hidden directories, node_modules, vendor, and friends). Anything it
// cannot describe becomes a hint on stdout rather than a guess in the
// file, so the generated configuration always loads and the surprises
// stay visible.
package scaffold

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"gopkg.in/yaml.v3"

	"github.com/HalxDocs/dashdev/internal/config"
)

// Service is one detected runnable thing.
type Service struct {
	// Name is unique within the report.
	Name string
	// Command is a verbatim argument list.
	Command []string
	// Directory is relative to the scanned directory. Empty means the
	// scanned directory itself, and is omitted from the rendered file.
	Directory string
}

// Report is what a scan found, plus what it noticed but could not use.
type Report struct {
	Services []Service
	Hints    []string
}

// directories that never contain a service worth starting.
var skipDirs = map[string]bool{
	".git": true, "node_modules": true, "vendor": true, "bin": true,
	"out": true, "dist": true, "build": true, "target": true,
	"docs": true, "testdata": true,
}

// Scan looks for runnable code in dir and describes what it found.
func Scan(dir string) (Report, error) {
	var found finder
	if err := found.scanRoot(dir); err != nil {
		return Report{}, err
	}
	return Report{Services: found.services, Hints: found.hints}, nil
}

// Render turns a report into a dashdev.yaml body. The header carries the
// hints so the context travels with the file, not just the terminal.
func Render(report Report) ([]byte, error) {
	var body strings.Builder
	body.WriteString("# Generated by `dashdev init`. Edit freely: every field\n")
	body.WriteString("# is the ordinary configuration format.\n")
	for _, hint := range report.Hints {
		body.WriteString("# " + hint + "\n")
	}
	document := fileDocument{Version: config.Version}
	for _, service := range report.Services {
		document.Services = append(document.Services, fileService{
			Name:      service.Name,
			Command:   service.Command,
			Directory: service.Directory,
		})
	}
	encoded, err := yaml.Marshal(&document)
	if err != nil {
		return nil, fmt.Errorf("scaffold: could not render the configuration: %w", err)
	}
	body.WriteString(string(encoded))
	return []byte(body.String()), nil
}

// fileDocument mirrors the on-disk schema tightly enough to render it.
// The authoritative schema stays in the config package; this one only
// writes the fields the detectors produce.
type fileDocument struct {
	Version  int           `yaml:"version"`
	Services []fileService `yaml:"services"`
}

type fileService struct {
	Name      string   `yaml:"name"`
	Command   []string `yaml:"command"`
	Directory string   `yaml:"directory,omitempty"`
}

// finder accumulates services and hints with unique names.
type finder struct {
	services []Service
	hints    []string
	used     map[string]bool
}

// scanDir inspects one module-ish directory: dir on disk, rel for output.
func (f *finder) scanDir(dir, rel string) error {
	if _, err := os.ReadDir(dir); err != nil {
		return fmt.Errorf("scaffold: cannot read %s: %w", displayDir(dir, rel), err)
	}
	if hasFile(dir, "go.mod") {
		f.scanGoModule(dir, rel)
	}
	if hasFile(dir, "package.json") {
		f.scanNodePackage(dir, rel)
	}
	for _, name := range []string{"requirements.txt", "pyproject.toml", "setup.py"} {
		if hasFile(dir, name) {
			f.hint(displayDir(dir, rel) + " looks like Python (" + name + "): add a service by hand, only Go and Node are scaffolded yet")
			break
		}
	}
	if hasFile(dir, "Cargo.toml") {
		f.hint(displayDir(dir, rel) + " looks like Rust (Cargo.toml): add a service by hand, only Go and Node are scaffolded yet")
	}
	return nil
}

// scanRoot walks the scanned directory and one level of subdirectories.
func (f *finder) scanRoot(dir string) error {
	if err := f.scanDir(dir, ""); err != nil {
		return err
	}
	entries, err := os.ReadDir(dir)
	if err != nil {
		return fmt.Errorf("scaffold: cannot read %s: %w", dir, err)
	}
	f.hints = append(f.hints, rootHints(entries)...)
	names := make([]string, 0, len(entries))
	for _, entry := range entries {
		if !entry.IsDir() || skipDirs[entry.Name()] || strings.HasPrefix(entry.Name(), ".") {
			continue
		}
		names = append(names, entry.Name())
	}
	sort.Strings(names)
	for _, name := range names {
		sub := filepath.Join(dir, name)
		if hasFile(sub, "go.mod") || hasFile(sub, "package.json") {
			if err := f.scanDir(sub, name); err != nil {
				return err
			}
		}
	}
	return nil
}

// scanGoModule adds a service per ./cmd entry point, or one `go run .`
// when the module itself is runnable.
func (f *finder) scanGoModule(dir, rel string) {
	cmdDir := filepath.Join(dir, "cmd")
	cmds, err := runnableCmds(cmdDir)
	if err == nil && len(cmds) > 0 {
		for _, cmd := range cmds {
			f.add(uniqueName(f.used, serviceName(rel, cmd)), []string{"go", "run", "./cmd/" + cmd}, rel)
		}
		return
	}
	if hasMainPackage(dir) {
		f.add(uniqueName(f.used, serviceName(rel, "app")), []string{"go", "run", "."}, rel)
	}
}

// scanNodePackage adds `npm run <script>`, preferring dev over start.
func (f *finder) scanNodePackage(dir, rel string) {
	raw, err := os.ReadFile(filepath.Join(dir, "package.json"))
	if err != nil {
		return
	}
	var manifest struct {
		Name    string            `json:"name"`
		Scripts map[string]string `json:"scripts"`
	}
	if err := json.Unmarshal(raw, &manifest); err != nil || len(manifest.Scripts) == 0 {
		return
	}
	script := ""
	for _, candidate := range []string{"dev", "start", "serve"} {
		if _, ok := manifest.Scripts[candidate]; ok {
			script = candidate
			break
		}
	}
	if script == "" {
		return
	}
	name := manifest.Name
	if rel != "" {
		name = rel
	}
	if name == "" {
		name = "app"
	}
	f.add(uniqueName(f.used, name), []string{"npm", "run", script}, rel)
}

// rootHints notices files that matter at the top level only.
func rootHints(entries []os.DirEntry) []string {
	var hints []string
	names := map[string]bool{}
	for _, entry := range entries {
		names[entry.Name()] = true
	}
	if names["docker-compose.yml"] || names["docker-compose.yaml"] || names["compose.yml"] || names["compose.yaml"] {
		hints = append(hints, "a compose file is present: run containers as a service with command [docker, compose, up] (foreground, never -d)")
	}
	if names[".env"] || names[".env.example"] {
		hints = append(hints, "services inherit your shell environment: source .env first (bash: set -a; source .env; set +a)")
	}
	return hints
}

func (f *finder) add(name string, command []string, rel string) {
	if f.used == nil {
		f.used = map[string]bool{}
	}
	f.used[name] = true
	f.services = append(f.services, Service{Name: name, Command: command, Directory: rel})
}

func (f *finder) hint(text string) {
	f.hints = append(f.hints, text)
}

// serviceName prefers the command name at the root and the directory
// base name below it, so ./cmd/keyway becomes "keyway" but ./api/cmd/api
// becomes "api".
func serviceName(rel, cmd string) string {
	if rel == "" {
		return cmd
	}
	return filepath.Base(rel)
}

func uniqueName(used map[string]bool, want string) string {
	if !used[want] {
		return want
	}
	for i := 2; ; i++ {
		candidate := fmt.Sprintf("%s-%d", want, i)
		if !used[candidate] {
			return candidate
		}
	}
}

func displayDir(dir, rel string) string {
	if rel != "" {
		return "./" + rel
	}
	return dir
}

func hasFile(dir string, names ...string) bool {
	for _, name := range names {
		info, err := os.Stat(filepath.Join(dir, name))
		if err == nil && !info.IsDir() {
			return true
		}
	}
	return false
}

// runnableCmds lists ./cmd subdirectories that contain Go files.
func runnableCmds(cmdDir string) ([]string, error) {
	entries, err := os.ReadDir(cmdDir)
	if err != nil {
		return nil, err
	}
	var cmds []string
	for _, entry := range entries {
		if !entry.IsDir() {
			continue
		}
		sub, err := os.ReadDir(filepath.Join(cmdDir, entry.Name()))
		if err != nil {
			continue
		}
		for _, file := range sub {
			if !file.IsDir() && strings.HasSuffix(file.Name(), ".go") {
				cmds = append(cmds, entry.Name())
				break
			}
		}
	}
	sort.Strings(cmds)
	return cmds, nil
}

// hasMainPackage reports whether dir itself holds a main package.
func hasMainPackage(dir string) bool {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return false
	}
	for _, entry := range entries {
		if entry.IsDir() || !strings.HasSuffix(entry.Name(), ".go") {
			continue
		}
		raw, err := os.ReadFile(filepath.Join(dir, entry.Name()))
		if err != nil {
			continue
		}
		if strings.Contains(string(raw), "func main(") {
			return true
		}
	}
	return false
}
